version: '2.4'

services:
  vpn:
    build:
      dockerfile: Dockerfile
      context: .
    command: ./run_vpn_client.sh
    cap_add:
      - NET_ADMIN
    networks:
      - docker-network-test

networks:
  docker-network-test:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.24.0.0/16
          gateway: 172.24.0.2