version: '2.4'

services:
  vpn_server:
    build:
      dockerfile: Dockerfile
      context: .
    command: ./run_vpn_server.sh
    ports:
      - ${VPN_SERVER_PORT:-45918}:${VPN_SERVER_PORT:-45918}
    environment:
      - VPN_SERVER_PORT=${VPN_SERVER_PORT:-45918}
  vpn_prov:
    build:
      dockerfile: Dockerfile
      context: .
    devices:
      - /dev/net/tun:/dev/net/tun
    command: ./run_vpn_prov.sh
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_CLIENT_ID=3445
      - VPN_IP=192.168.255.120
      - VPN_REQ_IP=192.168.255.121
      - VPN_SERVER_HOST=${VPN_SERVER_HOST:-vpn_server}
      - VPN_SERVER_PORT=${VPN_SERVER_PORT:-45918}
  vpn_req:
    build:
      dockerfile: Dockerfile
      context: .
    devices:
      - /dev/net/tun:/dev/net/tun
    command: ./run_vpn_req.sh
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_CLIENT_ID=3444
      - VPN_IP=192.168.255.121
      - VPN_PROV_IP=192.168.255.120
      - VPN_SERVER_HOST=${VPN_SERVER_HOST:-vpn_server}
      - VPN_SERVER_PORT=${VPN_SERVER_PORT:-45918}
