version: '2.4'

services:
  vpn_client:
    build:
      dockerfile: Dockerfile
      context: .
    command: ./run_vpn_client.sh
    cap_add:
      - NET_ADMIN
  vpn_server:
    build:
      dockerfile: Dockerfile
      context: .
    command: ./run_vpn_server.sh
    cap_add:
      - NET_ADMIN
    ports:
      - "45918:45918"
